// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: kube_controller_api/reconciler.proto

package controllerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReconcileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Error is the error message, if any.
	// If the error is unset, the processing is assumed to be successful.
	Error *string `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	// Requeue indicates that the object should be immediately requeued.
	// The default is false.
	Requeue bool `protobuf:"varint,2,opt,name=requeue,proto3" json:"requeue,omitempty"`
	// RequeueAfter indicates that the object should be requeued after the
	// given delay, if set to a value greater than 0.
	RequeueAfter *durationpb.Duration `protobuf:"bytes,3,opt,name=requeue_after,json=requeueAfter,proto3" json:"requeue_after,omitempty"`
	// Status is the new value to set for the status subresource, if specified.
	// It should be the JSON-encoded value of the `.status` field.
	Status []byte `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
}

func (x *ReconcileResult) Reset() {
	*x = ReconcileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kube_controller_api_reconciler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconcileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResult) ProtoMessage() {}

func (x *ReconcileResult) ProtoReflect() protoreflect.Message {
	mi := &file_kube_controller_api_reconciler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResult.ProtoReflect.Descriptor instead.
func (*ReconcileResult) Descriptor() ([]byte, []int) {
	return file_kube_controller_api_reconciler_proto_rawDescGZIP(), []int{0}
}

func (x *ReconcileResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ReconcileResult) GetRequeue() bool {
	if x != nil {
		return x.Requeue
	}
	return false
}

func (x *ReconcileResult) GetRequeueAfter() *durationpb.Duration {
	if x != nil {
		return x.RequeueAfter
	}
	return nil
}

func (x *ReconcileResult) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

type WorkQueue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ControllerName is the name of the controller.
	ControllerName string `protobuf:"bytes,1,opt,name=controller_name,json=controllerName,proto3" json:"controller_name,omitempty"`
}

func (x *WorkQueue) Reset() {
	*x = WorkQueue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kube_controller_api_reconciler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkQueue) ProtoMessage() {}

func (x *WorkQueue) ProtoReflect() protoreflect.Message {
	mi := &file_kube_controller_api_reconciler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkQueue.ProtoReflect.Descriptor instead.
func (*WorkQueue) Descriptor() ([]byte, []int) {
	return file_kube_controller_api_reconciler_proto_rawDescGZIP(), []int{1}
}

func (x *WorkQueue) GetControllerName() string {
	if x != nil {
		return x.ControllerName
	}
	return ""
}

type ChildObjects struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupVersionKind *GroupVersionKind `protobuf:"bytes,1,opt,name=group_version_kind,json=groupVersionKind,proto3" json:"group_version_kind,omitempty"`
	Objects          [][]byte          `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *ChildObjects) Reset() {
	*x = ChildObjects{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kube_controller_api_reconciler_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChildObjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildObjects) ProtoMessage() {}

func (x *ChildObjects) ProtoReflect() protoreflect.Message {
	mi := &file_kube_controller_api_reconciler_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildObjects.ProtoReflect.Descriptor instead.
func (*ChildObjects) Descriptor() ([]byte, []int) {
	return file_kube_controller_api_reconciler_proto_rawDescGZIP(), []int{2}
}

func (x *ChildObjects) GetGroupVersionKind() *GroupVersionKind {
	if x != nil {
		return x.GroupVersionKind
	}
	return nil
}

func (x *ChildObjects) GetObjects() [][]byte {
	if x != nil {
		return x.Objects
	}
	return nil
}

var File_kube_controller_api_reconciler_proto protoreflect.FileDescriptor

var file_kube_controller_api_reconciler_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6b, 0x75, 0x62, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6b, 0x75, 0x62, 0x65, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x24, 0x6b, 0x75, 0x62,
	0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69,
	0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb8, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x41, 0x66, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x01, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x34, 0x0a, 0x09,
	0x57, 0x6f, 0x72, 0x6b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x7d, 0x0a, 0x0c, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x12, 0x53, 0x0a, 0x12, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25,
	0x2e, 0x6b, 0x75, 0x62, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x10, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4c, 0x6f, 0x67, 0x69, 0x74, 0x73, 0x41, 0x49, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x2d, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_kube_controller_api_reconciler_proto_rawDescOnce sync.Once
	file_kube_controller_api_reconciler_proto_rawDescData = file_kube_controller_api_reconciler_proto_rawDesc
)

func file_kube_controller_api_reconciler_proto_rawDescGZIP() []byte {
	file_kube_controller_api_reconciler_proto_rawDescOnce.Do(func() {
		file_kube_controller_api_reconciler_proto_rawDescData = protoimpl.X.CompressGZIP(file_kube_controller_api_reconciler_proto_rawDescData)
	})
	return file_kube_controller_api_reconciler_proto_rawDescData
}

var file_kube_controller_api_reconciler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kube_controller_api_reconciler_proto_goTypes = []interface{}{
	(*ReconcileResult)(nil),     // 0: kube_controller_api.ReconcileResult
	(*WorkQueue)(nil),           // 1: kube_controller_api.WorkQueue
	(*ChildObjects)(nil),        // 2: kube_controller_api.ChildObjects
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
	(*GroupVersionKind)(nil),    // 4: kube_controller_api.GroupVersionKind
}
var file_kube_controller_api_reconciler_proto_depIdxs = []int32{
	3, // 0: kube_controller_api.ReconcileResult.requeue_after:type_name -> google.protobuf.Duration
	4, // 1: kube_controller_api.ChildObjects.group_version_kind:type_name -> kube_controller_api.GroupVersionKind
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kube_controller_api_reconciler_proto_init() }
func file_kube_controller_api_reconciler_proto_init() {
	if File_kube_controller_api_reconciler_proto != nil {
		return
	}
	file_kube_controller_api_controller_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_kube_controller_api_reconciler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconcileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kube_controller_api_reconciler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkQueue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kube_controller_api_reconciler_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChildObjects); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kube_controller_api_reconciler_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kube_controller_api_reconciler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kube_controller_api_reconciler_proto_goTypes,
		DependencyIndexes: file_kube_controller_api_reconciler_proto_depIdxs,
		MessageInfos:      file_kube_controller_api_reconciler_proto_msgTypes,
	}.Build()
	File_kube_controller_api_reconciler_proto = out.File
	file_kube_controller_api_reconciler_proto_rawDesc = nil
	file_kube_controller_api_reconciler_proto_goTypes = nil
	file_kube_controller_api_reconciler_proto_depIdxs = nil
}
