# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import controller_pb2 as controller__pb2
import reconciler_pb2 as reconciler__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmanager.proto\x12\ncontroller\x1a\x10\x63ontroller.proto\x1a\x10reconciler.proto\"W\n\x14\x43reateManagerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x31\n\x0b\x63ontrollers\x18\x02 \x03(\x0b\x32\x1c.controller.ControllerConfig\"#\n\x15\x43reateManagerResponse\x12\n\n\x02id\x18\x01 \x01(\t\"}\n\x14ReconcileLoopRequest\x12*\n\tsubscribe\x18\x01 \x01(\x0b\x32\x15.controller.WorkQueueH\x00\x12\x32\n\x0b\x61\x63knowledge\x18\x02 \x01(\x0b\x32\x1b.controller.ReconcileResultH\x00\x42\x05\n\x03msg\"\'\n\x15ReconcileLoopResponse\x12\x0e\n\x06object\x18\x01 \x01(\x0c\x32\xc7\x01\n\x11\x43ontrollerManager\x12V\n\rCreateManager\x12 .controller.CreateManagerRequest\x1a!.controller.CreateManagerResponse\"\x00\x12Z\n\rReconcileLoop\x12 .controller.ReconcileLoopRequest\x1a!.controller.ReconcileLoopResponse\"\x00(\x01\x30\x01\x42\x36Z4github.com/LogitsAI/kube-controller-api/controllerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manager_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z4github.com/LogitsAI/kube-controller-api/controllerpb'
  _globals['_CREATEMANAGERREQUEST']._serialized_start=65
  _globals['_CREATEMANAGERREQUEST']._serialized_end=152
  _globals['_CREATEMANAGERRESPONSE']._serialized_start=154
  _globals['_CREATEMANAGERRESPONSE']._serialized_end=189
  _globals['_RECONCILELOOPREQUEST']._serialized_start=191
  _globals['_RECONCILELOOPREQUEST']._serialized_end=316
  _globals['_RECONCILELOOPRESPONSE']._serialized_start=318
  _globals['_RECONCILELOOPRESPONSE']._serialized_end=357
  _globals['_CONTROLLERMANAGER']._serialized_start=360
  _globals['_CONTROLLERMANAGER']._serialized_end=559
# @@protoc_insertion_point(module_scope)
