# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kube_controller_api/controller.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$kube_controller_api/controller.proto\x12\x13kube_controller_api\"\x90\x01\n\x10\x43ontrollerConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x35\n\x06parent\x18\x02 \x01(\x0b\x32%.kube_controller_api.GroupVersionKind\x12\x37\n\x08\x63hildren\x18\x03 \x03(\x0b\x32%.kube_controller_api.GroupVersionKind\"@\n\x10GroupVersionKind\x12\r\n\x05group\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0c\n\x04kind\x18\x03 \x01(\tB6Z4github.com/LogitsAI/kube-controller-api/controllerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kube_controller_api.controller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/LogitsAI/kube-controller-api/controllerpb'
  _globals['_CONTROLLERCONFIG']._serialized_start=62
  _globals['_CONTROLLERCONFIG']._serialized_end=206
  _globals['_GROUPVERSIONKIND']._serialized_start=208
  _globals['_GROUPVERSIONKIND']._serialized_end=272
# @@protoc_insertion_point(module_scope)
